# # For lab controller
# joy_node:
#   ros__parameters:
#     device_id: 0
#     deadzone: 0.05
#     autorepeat_rate: 20.0

# teleop_node:
#   ros__parameters:
#     axis_linear:
#       x: 7
#     scale_linear:
#       x: 0.3
#     scale_linear_turbo:
#       x: 0.5

#     axis_angular:
#       yaw: 6
#     scale_angular:
#       yaw: 0.75
#     scale_angular_turbo:
#       yaw: 1.05


#     enable_button: 6
#     enable_turbo_button: 7

#     require_enable_button: true

#     publish_stamped_twist: true


# # For home controller
joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.3
    scale_linear_turbo:
      x: 0.5

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.75
    scale_angular_turbo:
      yaw: 1.05


    enable_button: 4
    enable_turbo_button: 5

    require_enable_button: true

    publish_stamped_twist: true